# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_play1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(581, 484)
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(80, 110, 401, 351))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.headerItem().setBackground(0, QtGui.QColor(170, 255, 0))
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.treeWidget.headerItem().setForeground(0, brush)
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(1, font)
        self.treeWidget.headerItem().setBackground(1, QtGui.QColor(170, 255, 127))
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.treeWidget.headerItem().setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.btnSetCheckBox = QtWidgets.QPushButton(Form)
        self.btnSetCheckBox.setGeometry(QtCore.QRect(220, 40, 75, 23))
        self.btnSetCheckBox.setObjectName("btnSetCheckBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "姓名"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "信息"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "张三"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "性别"))
        self.treeWidget.topLevelItem(0).child(0).setText(1, _translate("Form", "男"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Form", "年龄"))
        self.treeWidget.topLevelItem(0).child(1).setText(1, _translate("Form", "18"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Form", "爱好"))
        self.treeWidget.topLevelItem(0).child(2).setText(1, _translate("Form", "LOL"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "李四"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Form", "性别"))
        self.treeWidget.topLevelItem(1).child(0).setText(1, _translate("Form", "男"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Form", "年龄"))
        self.treeWidget.topLevelItem(1).child(1).setText(1, _translate("Form", "20"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Form", "爱好"))
        self.treeWidget.topLevelItem(1).child(2).setText(1, _translate("Form", "DOTA"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Form", "王五"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Form", "性别"))
        self.treeWidget.topLevelItem(2).child(0).setText(1, _translate("Form", "男"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Form", "年龄"))
        self.treeWidget.topLevelItem(2).child(1).setText(1, _translate("Form", "22"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Form", "爱好"))
        self.treeWidget.topLevelItem(2).child(2).setText(1, _translate("Form", "麻将"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Form", "芳芳"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("Form", "性别"))
        self.treeWidget.topLevelItem(3).child(0).setText(1, _translate("Form", "女"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("Form", "年龄"))
        self.treeWidget.topLevelItem(3).child(1).setText(1, _translate("Form", "20"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("Form", "爱好"))
        self.treeWidget.topLevelItem(3).child(2).setText(1, _translate("Form", "看书"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Form", "小智"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Form", "性别"))
        self.treeWidget.topLevelItem(4).child(0).setText(1, _translate("Form", "男"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Form", "年龄"))
        self.treeWidget.topLevelItem(4).child(1).setText(1, _translate("Form", "25"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("Form", "爱好"))
        self.treeWidget.topLevelItem(4).child(2).setText(1, _translate("Form", "解说"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Form", "婷婷"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("Form", "性别"))
        self.treeWidget.topLevelItem(5).child(0).setText(1, _translate("Form", "女"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("Form", "年龄"))
        self.treeWidget.topLevelItem(5).child(1).setText(1, _translate("Form", "27"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("Form", "爱好"))
        self.treeWidget.topLevelItem(5).child(2).setText(1, _translate("Form", "健身"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("Form", "大熊"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("Form", "性别"))
        self.treeWidget.topLevelItem(6).child(0).setText(1, _translate("Form", "男"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("Form", "年龄"))
        self.treeWidget.topLevelItem(6).child(1).setText(1, _translate("Form", "14"))
        self.treeWidget.topLevelItem(6).child(2).setText(0, _translate("Form", "爱好"))
        self.treeWidget.topLevelItem(6).child(2).setText(1, _translate("Form", "睡觉"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.btnSetCheckBox.setText(_translate("Form", "CheckBox"))
